# Generated by Django 3.2.3 on 2022-02-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20220219_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.user'),
        ),
    ]
