# Generated by Django 3.2.3 on 2022-02-21 17:07

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_posts_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='username',
            new_name='Username',
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='aurt',
            field=models.CharField(default=myapi.models.User, max_length=15),
        ),
    ]
