# Generated by Django 3.2.3 on 2022-02-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20)),
        ),
    ]
