# Generated by Django 3.2.3 on 2022-02-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_posts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
        migrations.AddField(
            model_name='posts',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
