# Generated by Django 3.2.3 on 2022-02-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20220222_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='num',
        ),
    ]
