# Generated by Django 3.2.3 on 2022-02-23 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_remove_posts_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('createdat', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('postcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapi.posts')),
            ],
        ),
    ]
