# Generated by Django 3.2.3 on 2022-02-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_alter_comment_postcom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postcom',
            new_name='post',
        ),
    ]
