# Generated by Django 3.2.3 on 2022-02-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('pass1', models.CharField(max_length=200)),
            ],
        ),
    ]
